name: LuckPerm-Display-Names-For-PAF
version: ${project.version}
author: Simonsator
depend: [ PartyAndFriends, LuckPerms ]
depends: [ PartyAndFriends, LuckPerms ]
main: de.simonsator.partyandfriends.extensions.luckperms.prefixes.bungee.configuration.PrefixesPermsPlugin
description: An add-on for party and friends to add display names from luckperm to the names
api-version: 1.13